// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9THanqcY0teMyTqLozaCFRkhmWDwimlY',
    appId: '1:63293861198:web:0ea5165d8f8bbc98a4821f',
    messagingSenderId: '63293861198',
    projectId: 'todoapp-a3825',
    authDomain: 'todoapp-a3825.firebaseapp.com',
    storageBucket: 'todoapp-a3825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCXYwQvar3YlYbi3oFOwZwKreZQMWBfs',
    appId: '1:63293861198:android:86ed0e611f3c2a53a4821f',
    messagingSenderId: '63293861198',
    projectId: 'todoapp-a3825',
    storageBucket: 'todoapp-a3825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQ_U2Y7WjS_CtpVg_OwXeWlkqpk8RApg',
    appId: '1:63293861198:ios:0c0accbd5eba7352a4821f',
    messagingSenderId: '63293861198',
    projectId: 'todoapp-a3825',
    storageBucket: 'todoapp-a3825.appspot.com',
    iosClientId: '63293861198-86mqiotni9fnunjkr3s6j39vq1cj3jnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQ_U2Y7WjS_CtpVg_OwXeWlkqpk8RApg',
    appId: '1:63293861198:ios:0c0accbd5eba7352a4821f',
    messagingSenderId: '63293861198',
    projectId: 'todoapp-a3825',
    storageBucket: 'todoapp-a3825.appspot.com',
    iosClientId: '63293861198-86mqiotni9fnunjkr3s6j39vq1cj3jnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
